<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Pierangelo's bakery]]></title>
  <link href="http://pierangeloc.github.io/atom.xml" rel="self"/>
  <link href="http://pierangeloc.github.io/"/>
  <updated>2014-10-23T07:39:20+02:00</updated>
  <id>http://pierangeloc.github.io/</id>
  <author>
    <name><![CDATA[Pierangelo Cecchetto]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[Some Notes About Java Certification Exam]]></title>
    <link href="http://pierangeloc.github.io/blog/2014/10/22/some-notes-about-java-certification-exam/"/>
    <updated>2014-10-22T21:37:45+02:00</updated>
    <id>http://pierangeloc.github.io/blog/2014/10/22/some-notes-about-java-certification-exam</id>
    <content type="html"><![CDATA[<p>With this post I am starting my blog, and I dedicate it (like probably the next few ones) to topics I am encountering during the preparation of the Java Professional Certification exam.
Even if you probably have been using Java for many years, Java certification offers an opportunity to discover details about the language and its features.
In the following notes I am collecting a few points that I found at least not obvious, either because I never had the chance to look into them before, or because they showed some peculiar behavior worth keeping in mind. The following notes refer to Java 7.</p>

<h4 id="precise-rethrow">Precise rethrow</h4>
<p>This is a feature that has been introduced in the Java 7 compiler, and it can be expressed in this way:<br />
<em>When rethrowing an exception, the rethrown type doesnâ€™t have necessarily to be of the same type declared in the <code>catch</code> block. If e.g. the <code>try</code> block can throw exceptions of type <code>E1</code>, <code>E2</code>, <code>E3</code> all subtypes of <code>E</code> which is the type in the <code>catch</code> clause, the rethrowing action is aware of being restricted to types <code>E1</code>, <code>E2</code>, <code>E3</code> and not necessarily to <code>E</code>.</em><br />
This can be easily better explained through an example</p>

<div class="bogus-wrapper"><notextile><figure class="code"><figcaption><span></span></figcaption><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
</pre></td><td class="code"><pre><code class="Java"><span class="line"><span class="kd">public</span> <span class="kd">class</span> <span class="nc">PreciseRethrow</span> <span class="o">{</span>
</span><span class="line">
</span><span class="line">    <span class="kd">public</span> <span class="kt">void</span> <span class="nf">rethrowException</span><span class="o">(</span><span class="n">String</span> <span class="n">exceptionOrdinal</span><span class="o">)</span> <span class="kd">throws</span> <span class="n">ExceptionB</span><span class="o">,</span> <span class="n">ExceptionA</span> <span class="o">{</span>
</span><span class="line">        <span class="k">try</span> <span class="o">{</span>
</span><span class="line">            <span class="k">if</span><span class="o">(</span><span class="n">exceptionOrdinal</span><span class="o">.</span><span class="na">equals</span><span class="o">(</span><span class="s">&quot;first&quot;</span><span class="o">))</span>
</span><span class="line">                <span class="k">throw</span> <span class="k">new</span> <span class="nf">ExceptionA</span><span class="o">();</span>
</span><span class="line">            <span class="k">else</span>
</span><span class="line">                <span class="k">throw</span> <span class="k">new</span> <span class="nf">ExceptionB</span><span class="o">();</span>
</span><span class="line">        <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="n">Exception</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
</span><span class="line">            <span class="n">e</span><span class="o">.</span><span class="na">printStackTrace</span><span class="o">();</span>
</span><span class="line">            <span class="n">Exception</span> <span class="n">f</span> <span class="o">=</span> <span class="n">e</span><span class="o">;</span>
</span><span class="line">            <span class="k">throw</span> <span class="n">f</span><span class="o">;</span>
</span><span class="line">        <span class="o">}</span>
</span><span class="line">    <span class="o">}</span>
</span><span class="line">
</span><span class="line"><span class="o">}</span>
</span><span class="line">
</span><span class="line"><span class="kd">class</span> <span class="nc">ExceptionA</span> <span class="kd">extends</span> <span class="n">Exception</span> <span class="o">{}</span>
</span><span class="line"><span class="kd">class</span> <span class="nc">ExceptionB</span> <span class="kd">extends</span> <span class="n">Exception</span> <span class="o">{}</span>
</span></code></pre></td></tr></table></div></figure></notextile></div>
<p>The compiler analyzes the code in the <code>try</code> clause and detects that only <code>FirstException</code> or <code>SecondException</code> can be thrown, therefore despite the <code>catch</code> block refers to a generic <code>Exception</code> class, it is aware that the actual exception being rethrown in the <code>throw e;</code> can either be of type <code>FirstException</code> or <code>SecondException</code>, therefore the <code>rethrowException()</code> method can declare <code>throws ExceptionB, ExceptionA</code> instead of <code>throws Exception</code>.<br />
If the exception being rethrown is copied to a variable local to the <code>catch</code> block which is in turn rethrown, like in this version of the <code>catch</code> block</p>

<div class="bogus-wrapper"><notextile><figure class="code"><figcaption><span></span></figcaption><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
</pre></td><td class="code"><pre><code class="Java"><span class="line"><span class="k">catch</span> <span class="o">(</span><span class="n">Exception</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
</span><span class="line">            <span class="n">e</span><span class="o">.</span><span class="na">printStackTrace</span><span class="o">();</span>
</span><span class="line">            <span class="n">Exception</span> <span class="n">f</span> <span class="o">=</span> <span class="n">e</span><span class="o">;</span>
</span><span class="line">            <span class="k">throw</span> <span class="n">f</span><span class="o">;</span>
</span><span class="line">        <span class="o">}</span>
</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>this nice behavior of the compiler ceases to occur, so it will produce a compilation error.</p>

<hr />
]]></content>
  </entry>
  
</feed>
